# Generated by Django 4.0.3 on 2022-04-09 00:28

from django.db import migrations, models
import idgenerator.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('position', models.CharField(max_length=60)),
                ('emergency_contact_name', models.CharField(max_length=120)),
                ('contact_number', models.CharField(max_length=13, verbose_name='emergency contact number')),
                ('address', models.TextField()),
                ('image', models.ImageField(upload_to=idgenerator.models.image_file_location)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
