# Generated by Django 4.0.3 on 2022-04-09 06:40

from django.db import migrations, models
import django.utils.timezone
import idgenerator.models


class Migration(migrations.Migration):

    dependencies = [
        ('idgenerator', '0003_idinfo_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='idinfo',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idinfo',
            name='blood_type',
            field=models.CharField(default='A', max_length=5),
        ),
        migrations.AlterField(
            model_name='idinfo',
            name='image',
            field=models.ImageField(help_text='Please upload square image', upload_to=idgenerator.models.image_file_location),
        ),
    ]
