# Generated by Django 4.0.3 on 2022-04-09 11:57

from django.db import migrations, models
import idgenerator.models


class Migration(migrations.Migration):

    dependencies = [
        ('idgenerator', '0004_idinfo_birth_date_idinfo_blood_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='idinfo',
            name='contact',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='idinfo',
            name='signature',
            field=models.ImageField(blank=True, help_text='Please upload square image', null=True, upload_to=idgenerator.models.image_file_location),
        ),
    ]
