# Generated by Django 4.0.3 on 2022-04-10 05:54

from django.db import migrations, models
import idgenerator.models


class Migration(migrations.Migration):

    dependencies = [
        ('idgenerator', '0005_idinfo_contact_idinfo_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='idinfo',
            name='barcode',
            field=models.ImageField(blank=True, upload_to=idgenerator.models.image_file_location),
        ),
    ]
