# Generated by Django 4.0.3 on 2022-04-10 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgenerator', '0006_idinfo_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idinfo',
            name='id_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
